### ISSUE TITLE
OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL "xxxxx"The request was aborted: The operation has timed out. 

### ISSUE THREAD

**Issue by Amit199083** [lukeis/selenium-gcode-issue-archive#8817]
The issue is occurring everytime when i am executing the script.Following are the details:
1.) ChromeDriver Version-2.30
2.) Browser -Chrome
3.) Language-C#

The issue is occurring at diferrent places ,sometimes it gets failed due to "click" command or sometimes during "sendkeys" command.

Let me know if more information is required.

**Comment by Amit199083** [comment]
LukeIS - The reason i am creating the issue again is because without nay comments you closed it.Please specify the comments .

**Comment by lukeis** [comment]
do not log issues here. log them in 
https://github.com/SeleniumHQ/selenium
