### ISSUE TITLE
How to Download file  using save.open dialog box in selenium

### ISSUE THREAD

**Issue by sharmayashraj** [lukeis/selenium-gcode-issue-archive#8843]
I am using selenium for my automation and I need to download file using selenium .
is there any way , we can achieve this without any third party tool?

I tried with Winium / AutoITX3 third party and I am able to download file using click on Save button from Download prompt.

after that I open new window and perform my testing when I closed newly opened window and want to switch to my old window where I download file using third party , I will not able to switch that window , it is always saying that timeout. If I not download file , then I am able to open window, switch to new window  and able to switch my last window without any problem.

is there any way where I can download file in internet explore using selenium only?

**Comment by ozelotdev** [comment]
README.md
> DO NOT LOG AN ISSUE HERE. THIS IS AN ARCHIVE ONLY
> Log new selenium issues here:
> https://github.com/seleniumhq/selenium/issues/new
