### ISSUE TITLE
Safari Extension Equivalent for safari version 11.0.2

### ISSUE THREAD

**Issue by Aravindhsc** [lukeis/selenium-gcode-issue-archive#8851]
<img width="1440" alt="screen shot 2017-12-27 at 11 50 24 am" src="https://user-images.githubusercontent.com/24908279/34372681-67da7dd8-eafc-11e7-90c6-ec4528d8b2cd.png">
 Hi,
I am trying to run my scripts on Safari. With my previous Safari version(10.0.3) with Safari driver extension(2.48) i could able to run my scripts successfully , but when my safari has been updated to 11.0.2 and with the safari driver extension; it is not even launching the url which i am passing and i was thrown with an error as "Configuration Failure. Error: Failed to connect to SafariDriver after 10065 ms". And i don't find any latest Safari driver extension other than 2.48 . Kindly someone help me with this. @selenium-ci  @lukeis

**Comment by jimevans** [comment]
This is an archived set of issues and is not a forum for reporting Selenium issues. Moreover, the use of the Safari extension to automate Safari has been deprecated for over a year, at the time of this writing. The proper method to automate Safari 11 and above is to use Apple’s Safari driver, which ships with the browser and can be used natively with Selenium 3.x.
