### ISSUE TITLE
Unable to handle web authenication using selenium webdriver

### ISSUE THREAD

**Issue by mohannautiyal** [lukeis/selenium-gcode-issue-archive#8856]
I have a web application which when launched manually gives me a windows popup asking for entering my credentials.

However, when I launch the appllication using webdriver it doesn't give me the popup window. It simply says authentication failed, Below is the error i get:

"Unauthorized"
The server could not verify that you are authorized to access the dcoument requested....."

How can I enter the credentials when it doesn't give me the option to enter the credentials. Manually it gives me the option to enter the enter the credentials but using webdriver it doesn't

**Comment by jimevans** [comment]
This issue repository is not active. No action will be taken on any issues opened in this repository.
