### ISSUE TITLE
chrome driver fails to enable and disable the proxy settings using PAC

### ISSUE THREAD

**Issue by Ashwini-Devi** [lukeis/selenium-gcode-issue-archive#8866]
I try to add anauto proxy url to enable the proxy but it fails to enable it.

proxy.setProxyAutoconfigUrl(autoProxyURL);
proxy.setProxyType(ProxyType.PAC);

Is there any other way to give a solution for this .

**Comment by ddavison** [comment]
hi @JeffGaly , please refer to the [Selenium-Users Google Group](https://groups.google.com/forum/#!forum/selenium-users) for context-specific questions.  if you find an actual issue with Selenium, please report it in the [project issues](https://github.com/seleniumhq/selenium/issues).
