### ISSUE TITLE
No Such element exception in IE browser 

### ISSUE THREAD

**Issue by shreyagupta24** [lukeis/selenium-gcode-issue-archive#8867]
Log new selenium issues here:

https://github.com/seleniumhq/selenium/issues/new
browser : IE
Selenium version :3.12.0
IE version: 11

I have a script executed in chrome and firefox .If i execute same script on IE throwing no such element expection . Below is the expection

java.lang.Exception: java.lang.Exception: Not found the element: //input[@id='username']
	at com.suite.Steps.doSuccessfulLogin(Steps.java:100)
	at ✽.I log in with username: '***************' and password: '**********'(src/test/resources/TestRunner/C501_ClickSignButtonOpen.feature:4)
Caused by: java.lang.Exception: Not found the element: //input[@id='username']

This issue will be closed immediately without any comment if you log it here. You will also receive animosity from project members for your willful disregard of this notice.

**Comment by jimevans** [comment]
The original issue template has this text in it:

### DO NOT LOG AN ISSUE HERE. THIS IS AN ARCHIVE ONLY

Log new selenium issues here:

https://github.com/seleniumhq/selenium/issues/new

As noted in the comment at the bottom of the issue template, "This issue will be closed immediately... if you log it here."
