### ISSUE TITLE
Not able to enter authentication pop up through autoit , if current open page url is different than the one for which credentials are required.

### ISSUE THREAD

**Issue by rupam25** [lukeis/selenium-gcode-issue-archive#8871]
In my company, if you launch firefox some intracomm webpage will opened up then authentication pop up starts appearing.If you enter proxy credentials then only you can do any further work.

NOTE: Opened intracomm page and url for which credentails are required both are different.

I try to pass credentials through autoit BUt it is not working.
used code :+1: 
ProfilesIni profile = new ProfilesIni();
            FirefoxProfile testprofile = profile.getProfile("debanjan");
            DesiredCapabilities dc = DesiredCapabilities.firefox();
            dc.setCapability(FirefoxDriver.PROFILE, testprofile);
            FirefoxDriver driver = new FirefoxDriver(dc);
            driver.manage().window().maximize();
            driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
             driver = new FirefoxDriver();
                Runtime.getRuntime().exec("H:\\Officialdata1\\AUTOITScript\\HandlePopUp.exe");

driver.get("http:\\www.google.com");

autoit code:
WinWaitActive("Authentication Required")
Send("user")
Send("{TAB}")
Send("pass")
Send("{ENTER}")

**Comment by diemol** [comment]
@rupam25 this is the issue archive, please do not open issues here.

If you have an issue than can be reproducible, please open it [here](https://github.com/SeleniumHQ/selenium/issues/new), don't forget to fill the complete template. Otherwise it is very likely that it will get closed.
